### ISSUE TITLE
Identify the list of sub-topics to cover

### ISSUE THREAD

**Issue by akhmerov** [olras/olras#10]
These should be described in the umbrella chapter

**Comment by vfatemi** [comment]
Copying the initial list of ideas from the hackmd

- What are ABSs and where are they found
- Structure of this review: we divide the following chapters by the following contexts in which ABS are found (one paragraph per red line)
    - Super-semi structures
    - ABS as qubits
    - Vortices
    - metallic weak links
    - multi-terminal
    - unconventional superconductors

**Comment by andrenmelo** [comment]
Do we also want to talk about magnetic systems, i.e. CdGM and YSR states? I'm not sure to what extent these can be considered ABS, though they are subgap states resulting from spatial variations of the order parameter.

**Comment by vfatemi** [comment]
Perhaps we can treat those after the first set of more traditional ABS.
