### ISSUE TITLE
Migrate the planning document and discussions

### ISSUE THREAD

**Issue by akhmerov** [olras/olras#15]
For completeness I link our planning document https://hackmd.io/VvVVFTd5TmaMfZ43nwpCtQ ; the chat discussions stay private

@andrenmelo @vfatemi can you check the issue list and see if I forgot to include something?

**Comment by andrenmelo** [comment]
@akhmerov I went through the document and it looks like you've caught everything.

**Comment by akhmerov** [comment]
Very good, closing.
